name: CI - Deploy Application with GitHub Pages

on:
  push:
    branches: ['master']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm --prefix webapp ci --legacy-peer-deps
    - run: npm --prefix webapp test --coverage --watchAll

  deploy:
    name: Publish to GitHub Pages
    needs: [tests]
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latests
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: bitovi/github-actions-react-to-ghp@v1.1.1
        with:
          path: build
    

