name: CI - Deploy Application with GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          npm --prefix webapp ci
          CI=false && npm --prefix webapp run build

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp/build
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
          cname: ${{ secrets.REACT_APP_BASEPATH }}
          commit_message: ${{ github.event.head_commit.message }}
          commit_user_name: ${{ github.event.head_commit.author.name }}
          commit_user_email: ${{ github.event.head_commit.author.email }}
          keep_files: true
          allow_empty_commit: true
          fqdn: ${{ secrets.REACT_APP_BASEPATH }}

        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_BASEPATH: ${{ secrets.REACT_APP_BASEPATH }}
          REACT_APP_NODE_ENV: ${{ secrets.REACT_APP_NODE_ENV }}
